name: Compile

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Compile LaTeX documents
              uses: xu-cheng/latex-action@v3
              with:
                  root_file: presentation.tex
                  working_directory: latex

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: PDF
                  path: presentation.pdf
